Change relation with the apt module
Source of error with puppetlabs-apt/1.8.0:

```
Error: Failed to apply catalog: Found 1 dependency cycle:
(Anchor[apt::source::aptly] => Apt::Source[aptly] => Class[Apt::Update]
=> Exec[apt_update] => Class[Apt::Update] => Anchor[apt::source::aptly])
```

There is no need to ask the Apt module how things work; it knows that
adding a source requires an update. The update is anchored in the  class
so requirering the class is just enough.